### ISSUE TITLE
Work With Encrypted Configs

### ISSUE THREAD

**Issue by KaspianDev** [germanztz/gnome-shell-extension-rclone-manager#11]
As in title, currently that does not work.

**Comment by germanztz** [comment]
Hi  @KaspianDev , can you specify the process for me in order to replicate the problem?
thanks

**Comment by KaspianDev** [comment]
Is this planned in near future @germanztz ?

**Comment by germanztz** [comment]
Hi Kaspian I'm glad to announce that I implemented than on release 43.1. Chers!

**Comment by KaspianDev** [comment]
> Hi Kaspian I'm glad to announce that I implemented than on release 43.1. Chers!

Thanks!
