### ISSUE TITLE
Two strange errors

### ISSUE THREAD

**Issue by crawfordlong** [germanztz/gnome-shell-extension-rclone-manager#16]
I'm going to collapse these into a single post because I have a hunch they are related even though they are completely different. First, platform:

Fedora 36, fully updated
Thinkpad X1
rclone 1.57.0-DEV (whatever was in the fedora repo)

ISSUE 1: Rogue config

I have 3 configs, onedrive, pcloud, and google drive. All are working. But on startup and occasionally at other times (I haven't pinned down the pattern, but it may be as simple as logging in or waking up), I receive a "Failed to create file system" error that the config is not in the rclone.conf config file. Call it "config4". This was a config I had previously created before I started using this extension and stopped using. Installing the extension seems to have brought it back from the dead, but I can't find any logs to track down what might be happening.

ISSUE 2: "... was already mounted"

Some time after login (and starting up the extension) the toolbar icon changes to a warning and all 3 of my configs have the same log entries: one or more "[config name] is already mounted" errors. 

There is only one rclone conf file in my system and it contains only the 3 configs that should be present. So I'm mystified about where config4 is coming from. But I'm wondering if there might be some second extension config somewhere that, for some reason, is firing multiple times AND is attempting to fire up an old config ... somehow.

QUESTION: 

My question is pretty simple: what information would you need to troubleshoot and how can I provide it? I've turned on debug mode but I don't see a log generating or anything. Happy to provide whatever info you need to track this down.

**Comment by germanztz** [comment]
Hi @crawfordlong , thanks for your feedback.
ISSUE 1: It feels like some rclone issue. This extension won't change nor edit the rclone configuration file by itself. All the actions are made thru rclone commands (except for backup/restore)
Try this: when you spot the rogue config, exec in terminal
`$ rclone listremotes`
Then, if you want to get rid of it:
`$ rclone config delete <rogue>`

If that command does not delete it, try cleaning the config file by hand

ISSUE 2: Not an error, just an info message. This extension won't umount drives by itself. When the system resets the extension, it will check for the mounts and inform that the drive didn't need to be mounted again, just ignore de message

QUESTION:
there:
https://github.com/germanztz/gnome-shell-extension-rclone-manager/blob/master/DEVELOP.md#debug
thanks again!

**Comment by crawfordlong** [comment]
Regarding issue 2 (sorry to reopen this), the concern is that the toolbar icon is *always* showing up as a warning triangle after the first few minutes. So maybe it's not that info message? 

Re: issue 1, I had already tried to `listremotes` and the rogue is not showing in the list. Bizzarely, it's also not showing up in a full system `find` except in snapshots. It's not hurting anything, and the only correlation I can even get a hint of is (was) with the extension. 

(If anyone is looking at this in the future, btw, this is a nice little single-purpose extension that does exactly what it says on the box.)

**Comment by germanztz** [comment]
Hi, I see the problem now, maybe you not using the last version of the extension. Tell me what version, you'll find it en about menu. Also Please, enable the debug option in settings and attach the logs described here (the method may differ in your linux ditro):
 https://github.com/germanztz/gnome-shell-extension-rclone-manager/blob/master/DEVELOP.md#debug
Thanks

**Comment by crawfordlong** [comment]
Will do. As a preliminary experiment, I nuked rclone entirely and removed
the extension, reinstalled rclone, and reconfigured the configs as
services. Everything is working at this point. The 3 configs I have are my
core workflows, so I'm good there, but I will reinstall the extension (from
gnome extensions website) and create another config and see what happens.
It may be a couple of days because of the US holiday.

**Comment by germanztz** [comment]
Hi! I fixed that, let me know if you get the same error again. Thanks!
