### ISSUE TITLE
[Feat] Gnome 43 support

### ISSUE THREAD

**Issue by KaspianDev** [germanztz/gnome-shell-extension-rclone-manager#21]
As in title ^^

**Comment by germanztz** [comment]
I'm on it! but it won't work yet. Why they breaking everything in every update!! keep you updated

**Comment by KaspianDev** [comment]
@germanztz 
I tried adding new gnome version to this list > https://github.com/germanztz/gnome-shell-extension-rclone-manager/blob/master/metadata.json#L5
And it seems to work fine :+1:

**Comment by germanztz** [comment]
You got It! thanks for you comment
