### ISSUE TITLE
[Feature Request] add bisync support

### ISSUE THREAD

**Issue by hideki2k02** [germanztz/gnome-shell-extension-rclone-manager#33]
Hello! Although you could easily change up the sync/reconnect commands, It would be really nice if you added options related to bisync.

Here's an example of what I did for sync and reconnect (reconnect only has a --resync at the end)
```
rclone --password-command %pcmd bisync %source %profile: --filters-file /home/hideki2k02/.config/rclone/filter.md --create-empty-src-dirs --compare modtime,checksum --drive-skip-gdocs -P -v
```

**Comment by germanztz** [comment]
Hi! thanks for the input! I just learn about bisync, the manual says it is in beta version. But I don't quite understand the goal of it. I think bisync can do all the work and the extension would not be needed anymore. I'll look into it

Thanks again!
