### ISSUE TITLE
Plans to add support for Gnome 47?

### ISSUE THREAD

**Issue by Cybercountry** [germanztz/gnome-shell-extension-rclone-manager#34]
Hello, 
I thank everyone involved with this project and I would really like to see its support being continued in gnome 47. Thank you very much

**Comment by mueckinger** [comment]
+1

**Comment by Cybercountry** [comment]
> +1

I managed to get the extension working on Gnome 47 by editing the `metadata.json` file (located at `~/.local/share/gnome-shell/extensions/rclone-manager@germanztz.com/`). I added '47' to the 'shell-version' list and it's now working.

![image](https://github.com/user-attachments/assets/48f60583-81e5-4197-931f-63f91df7b03a)

**Comment by germanztz** [comment]
Hi guys! I'm working on it, sorry for the delay

thanks!

**Comment by germanztz** [comment]
I uploaded it, waiting for aproval!
https://extensions.gnome.org/extension/5006/rclone-manager/
